apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  clusterIP: None
  selector:
    app: postgres-db
  ports:
  - port: {{ .Values.service.db.port }}
    targetPort: {{ .Values.service.db.targetPort }}
    name: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
spec:
  serviceName: postgres-db
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        image: {{ .Values.image.db }}
        ports:
        - containerPort: {{ .Values.service.db.targetPort }}
        env:
        - name: POSTGRES_DB
          value: "userdb"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - admin
            - -d
            - userdb
          initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.periodSeconds }}
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - admin
            - -d
            - userdb
          initialDelaySeconds: {{ .Values.probes.readinessInitialDelaySeconds }}
          periodSeconds: {{ .Values.probes.periodSeconds }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
