apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: logger
            image: busybox
            command:
            - /bin/sh
            - -c
            - echo "CronJob executed at $(date)" > /proc/1/fd/1
          restartPolicy: OnFailure
